/*----- PROTECTED REGION ID(DeviceMemLeakClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        DeviceMemLeakClass.h
//
// description : Include for the DeviceMemLeak root class.
//               This class is the singleton class for
//                the DeviceMemLeak device class.
//               It contains all properties and methods which the 
//               DeviceMemLeak requires only once e.g. the commands.
//
// project :     DeviceMemLeak
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef DeviceMemLeakClass_H
#define DeviceMemLeakClass_H

#include <tango.h>
#include <DeviceMemLeak.h>


/*----- PROTECTED REGION END -----*/	//	DeviceMemLeakClass.h


namespace DeviceMemLeak_ns
{
/*----- PROTECTED REGION ID(DeviceMemLeakClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	DeviceMemLeakClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute attr1 class definition
class attr1Attrib: public Tango::Attr
{
public:
	attr1Attrib():Attr("attr1",
			Tango::DEV_ENCODED, Tango::READ) {};
	~attr1Attrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<DeviceMemLeak *>(dev))->read_attr1(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<DeviceMemLeak *>(dev))->is_attr1_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command Start class definition
class StartClass : public Tango::Command
{
public:
	StartClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	StartClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~StartClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<DeviceMemLeak *>(dev))->is_Start_allowed(any);}
};

//	Command Stop class definition
class StopClass : public Tango::Command
{
public:
	StopClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	StopClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~StopClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<DeviceMemLeak *>(dev))->is_Stop_allowed(any);}
};

//	Command PushEncodedEvent class definition
class PushEncodedEventClass : public Tango::Command
{
public:
	PushEncodedEventClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	PushEncodedEventClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~PushEncodedEventClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<DeviceMemLeak *>(dev))->is_PushEncodedEvent_allowed(any);}
};


/**
 *	The DeviceMemLeakClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  DeviceMemLeakClass : public Tango::DeviceClass
#else
class DeviceMemLeakClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(DeviceMemLeakClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	DeviceMemLeakClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static DeviceMemLeakClass *init(const char *);
		static DeviceMemLeakClass *instance();
		~DeviceMemLeakClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		DeviceMemLeakClass(string &);
		static DeviceMemLeakClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	DeviceMemLeak_H
